pub mod binance;
pub mod bot_executor;
pub mod client;
pub mod orchestrator;
pub mod polymarket;
pub mod position;
pub mod strategy;
pub mod websocket;

pub use binance::client::BinanceClient;
pub use binance::client::btc_price_stream;
pub use binance::ticker::PriceUpdate;
pub use binance::kline::KlineUpdate;
pub use bot_executor::StrategyExecutor;
pub use client::ClobClient;
pub use polymarket::{ApiKeyCreds, PolymarketClient, StoredCredentials, BalanceAllowance, ValidationResult, PositionInfo};
pub use position::{Position, PositionManager, PositionSide, kelly_size};
pub use strategy::{StrategyParams, StrategyState};
pub use websocket::{get_mid_price, get_spread, OrderBook, OrderBookClient, OrderBookLevel};
pub use orchestrator::{BotOrchestrator, BotEvent, RunningBot, start_orchestrator_loop, start_auto_save_loop};
